controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]
    wheel_separation: 0.288
    wheel_radius: 0.033
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
    publish_rate: 50.0
    linear.x.max_velocity: 0.26
    linear.x.min_velocity: -0.26
    angular.z.max_velocity: 1.82
    angular.z.min_velocity: -1.82

arm_controller:
  ros__parameters:
    use_sim_time: true
    joints: [joint1, joint2, joint3, joint4]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: true

gripper_controller:
  ros__parameters:
    use_sim_time: true
    joints: [gripper_left_joint]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
